<form  method="POST" class="needs-validation main" novalidate>
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">Event Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminEvent') ?>">Event</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?= $form->csrfField('noob') ?>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field('title'); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field('slug'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('content'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-5">
                                <?= $form->field('cover-url'); ?>
                                <?= $form->field('cover-label'); ?>
                                <?= $form->field('address'); ?>
                                <?= $form->field('ages'); ?>

                                <?php if(module_exists('admin-event-profile')): ?>
                                    <?= $form->field('price'); ?>

                                    <?php if(module_exists('admin-event-venue')): ?>
                                        <?= $form->field('organizer', $opts['organizer']); ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <div class="col-md-7">
                                <?= $form->field('embed'); ?>
                                
                                <?php if(module_exists('admin-event-profile')): ?>
                                    <?= $form->field('performers') ?>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <?= $form->field('time_start'); ?>
                                        </div>
                                        <div class="col-md-6">
                                            <?= $form->field('time_end'); ?>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <?= $form->field('price'); ?>
                                    <?php if(module_exists('admin-event-venue')): ?>
                                        <?= $form->field('organizer', $opts['organizer']); ?>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <?= $form->field('time_start'); ?>
                                            </div>
                                            <div class="col-md-6">
                                                <?= $form->field('time_end'); ?>
                                            </div>
                                        </div>
                                    <?php else: ?>
                                        <?= $form->field('time_start'); ?>
                                        <?= $form->field('time_end'); ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <?= $this->partial('site-meta/meta'); ?>
                    </div>
                </div>
                <div class="card mt-3">
                    <div class="card-body">
                        <?= $form->field('socials-facebook'); ?>
                        <?= $form->field('socials-instagram'); ?>
                        <?= $form->field('socials-youtube'); ?>
                        <?= $form->field('socials-twitter'); ?>
                        <?= $form->field('socials-website'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
